title: My Celestial Inheritance
description: >- # this means to ignore newlines until "baseurl:"
  The stars left it to him, the fire delivered it, and I’m the only one who remembers what it’s worth.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "jgjr.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: hyde